# Generated by Django 3.0.3 on 2020-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('Nep', 'Nepal'), ('Ind', 'India'), ('US', 'USA'), ('UK', 'United Kingdom'), ('Cananda', 'Canada')], max_length=30)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
